# Generated by Django 3.0.2 on 2020-02-01 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_prev', models.CharField(default='', max_length=255)),
                ('link_full', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='ImageFragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('x_lt', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('y_lt', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('x_rb', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('y_rb', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('image', models.ForeignKey(blank=True, db_column='image_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Фрагмент изображения',
                'verbose_name_plural': 'Фрагменты изображения',
                'db_table': 'image_fragments',
            },
        ),
    ]
