# Generated by Django 3.0.2 on 2020-02-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefragment',
            name='is_chosen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
